version: '3.8'

services:
  app:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      PORT: 3002
      JWT_SECRET: secret.01
      DB_URI: mongodb://mongo:27017/mydatabase
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
